### ISSUE TITLE
The step parameter is not being used

### ISSUE THREAD

**Issue by sejr1996** [ErnaneJ/svelte-star-rating#1]
You should correct the step, since it is not referenced anywhere.
`step={config.range.step}`

**Comment by ErnaneJ** [comment]
Hi,

You are right. The purpose of the 'step' attribute would be to specify the range between allowed numbers in the scoring range.

You can see that this was resolved on here [`8f8e383`](https://github.com/ErnaneJ/svelte-star-rating/commit/8f8e3834c9572b3e89f17088c39bbf42e5ca00a0).

Thank you!
