### ISSUE TITLE
Bug: Not unique linearGradient id when component is used multiple times

### ISSUE THREAD

**Issue by korzhanov** [ErnaneJ/svelte-star-rating#12]
### Problem: 
When we use a component multiple times on a page as a form control, we get glitches when editing: the fill of the stars jumps and/or becomes the same in different components with the same value.

### Reason: 
the same `id` for linear SVG gradients on the same document page

### Solution option: 
Add `id` uniqueness, e.g. add `uuid` or `config.name` to `id`

```svelte
<!--  Stars.svelte -->

<Star id={config.name+id} .../>

```

**Comment by ErnaneJ** [comment]
Hi @korzhanov, this is indeed an intriguing bug. After investigating, I was able to replicate the error and resolved it in this commit: https://github.com/ErnaneJ/svelte-star-rating/commit/5d0be19640724b650051f78c37aedc1410f2d40a. I'll be releasing the new version [1.1.5](https://github.com/ErnaneJ/svelte-star-rating/releases/tag/v1.1.5) shortly, which will include this fix. Thank you!
