### ISSUE TITLE
Read only on:click event

### ISSUE THREAD

**Issue by Tam2** [ErnaneJ/svelte-star-rating#14]
Hello - When it's in a `readOnly: true` mode it still shows the pointer as if it's clickable

But there doesn't appear to be any `on:click` event handler.

I want to trigger a function on click when it's in readOnly mode to open up a modal, i tried `on:change` but that doesn't seem to do anything when in readOnly

**Comment by ErnaneJ** [comment]
Hey there! Thanks a bunch for bringing this issue to our attention. The pull request https://github.com/ErnaneJ/svelte-star-rating/pull/15 from @Thiteago addresses the concerns raised. Could you please give it a try now? I'm going to close this issue, but if you have any further questions or need assistance, don't hesitate to drop a comment!
