### ISSUE TITLE
How to get the value of it when it changes?

### ISSUE THREAD

**Issue by bostondevin** [ErnaneJ/svelte-star-rating#2]
How do I do this?

It doesn't look like there is any onChange event I can look at...

**Comment by ErnaneJ** [comment]
I don't know if I understood correctly what you want @bostondevin.

If it's just some way to capture the values ​​when they change at runtime, this can be done through the configuration object itself as follows:

```svelte
<StarRatting bind:config/>
```

That way when changing `config` in the component context it will be reflected in its root scope `config` variable and so you can use it normally to capture the values.

**Comment by ErnaneJ** [comment]
I will close this issue due to inactivity, but any other questions, you can reopen this topic or any other by starting a new question.

**Comment by Jojoshua** [comment]
I also would like a specific handler I can hook into like on:change where I can run code. I tried doing this by capturing via a reactive block but it was firing many times even when nothing was being clicked on.

**Comment by ErnaneJ** [comment]
Okay, I understand the need. I will evaluate your [PR#4](https://github.com/ErnaneJ/svelte-star-rating/pull/4).

**Comment by ErnaneJ** [comment]
Change accepted. Thanks so much for contributing! You can check out the merged change [here](https://github.com/ErnaneJ/svelte-star-rating/commit/c56a83877a5f5a7c63db51052d98cb8927b32636).
