### ISSUE TITLE
showScore as configurable function

### ISSUE THREAD

**Issue by Yelinz** [ErnaneJ/svelte-star-rating#7]
First of all really cool and nicely implemented rating component.

It would be nice to be able to format the displayed score however you wish. Just the config as parameter and the current implementation could be the default.

If you dont have the capacity, let me know, I could try to implement it.

**Comment by ErnaneJ** [comment]
Hey, thanks a lot for that!

This is a great suggestion, but I'm not sure I fully understand what you want. Could you explain a little more?

Also, I'm linked to a few other projects that might delay this delivery a bit so if you'd like, I'd love to get your PR on these implementations. What do you think?

Thanks!

**Comment by Yelinz** [comment]
I think the current percentage display is not very helpful. Instead having the display be customizable for example displaying 4.5/5 or whatever the function returns.

Currently it is `(config.score/config.countStars)*100).toFixed(2)`.
This would be about what I would like to display `{config.score}/{config.range.max}`

To accommodate custom formats a function instead of true/false for showScore would be more useful

**Comment by ErnaneJ** [comment]
Ah, now I understand. That makes a lot of sense to me! I saw your PR (#8) that tries to implement this feature, I will focus on it and implement it.

**Comment by ErnaneJ** [comment]
We have an open PR (#9) for this implementation. I will close an issue.

**Comment by Yelinz** [comment]
Thank you very much for the awesome and quick work!
